#!/bin/zsh
me=$0:a:h
zparseopts -D -E -F - s:=_s d:=_d o:=_o l:=_l
rsour=${_s[2]:-}
rdest=${_d[2]:-}
ropt=${_o[2]:-}
# rlist=${_l[2]:-"$(< $me/rlist)"}
if [[ -z ${_l[2]} ]]; then
 rlist=$(< $me/rlist)
else
 rlist=${(s: :)_l[2]}
fi
> $me/out


# while read rel
# do
#   echo $rsour $rdest $ropt $rel | tee -a $me/out
# done <<<$rlist

for rel in "${rlist[@]}"
do
 echo $rsour $rdest $ropt $rel | tee -a $me/out
done




